### ISSUE TITLE
i want to get your original dataset

### ISSUE THREAD

**Issue by xiaoc57** [lrnzgiusti/MaRF#3] opened 2024-01-28 15:54 UTC
Can you share a Google download link for the dataset used in the paper?

**Comment by houyongkuo** [comment] 2024-07-24 06:49
I saw from the paper that the data should come from NASA's Planetary Data System (PDS), but I can only locate this page (https://ode.rsl.wustl.edu/mars/productsearch). I haven't found which dataset it is yet.

**Comment by houyongkuo** [comment] 2024-07-24 07:58
Duplicate of #2

**Comment by lrnzgiusti** [comment] 2024-08-05 07:51
Thanks! Actually I recommend to look for new acquisitions on the pds:

https://planetarydata.jpl.nasa.gov/img/data/mars2020/

**Closed as completed** 2024-08-15 15:19 UTC
